src/Entity/Asset.php
<?php

namespace App\Entity;

use App\Repository\AssetRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AssetRepository::class)]
class Asset
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $asset_tag;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $serial_number;

    #[ORM\Column(type: 'boolean')]
    private $NeedsRepair;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $notes;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAssetTag(): ?string
    {
        return $this->asset_tag;
    }

    public function setAssetTag(string $asset_tag): self
    {
        $this->asset_tag = $asset_tag;

        return $this;
    }

    public function getSerialNumber(): ?string
    {
        return $this->serial_number;
    }

    public function setSerialNumber(?string $serial_number): self
    {
        $this->serial_number = $serial_number;

        return $this;
    }

    public function isNeedsRepair(): ?bool
    {
        return $this->NeedsRepair;
    }

    public function setNeedsRepair(bool $NeedsRepair): self
    {
        $this->NeedsRepair = $NeedsRepair;

        return $this;
    }

    public function getNotes(): ?string
    {
        return $this->notes;
    }

    public function setNotes(?string $notes): self
    {
        $this->notes = $notes;

        return $this;
    }
}

src/Entity/Repair.php
<?php

namespace App\Entity;

use App\Repository\RepairRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RepairRepository::class)]
class Repair
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'integer')]
    private $assetid;

    #[ORM\Column(type: 'integer')]
    private $personid;

    #[ORM\Column(type: 'integer')]
    private $technicianid;

    #[ORM\Column(type: 'datetime_immutable')]
    private $createdAt;

    #[ORM\Column(type: 'datetime_immutable')]
    private $modifiedAt;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $cartSlotId;

    #[ORM\Column(type: 'boolean')]
    private $active;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private $closedAt;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $notes;

    #[ORM\Column(type: 'array', nullable: true)]
    private $items = [];

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAssetid(): ?int
    {
        return $this->assetid;
    }

    public function setAssetid(int $assetid): self
    {
        $this->assetid = $assetid;

        return $this;
    }

    public function getPersonid(): ?int
    {
        return $this->personid;
    }

    public function setPersonid(int $personid): self
    {
        $this->personid = $personid;

        return $this;
    }

    public function getTechnicianid(): ?int
    {
        return $this->technicianid;
    }

    public function setTechnicianid(int $technicianid): self
    {
        $this->technicianid = $technicianid;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getModifiedAt(): ?\DateTimeImmutable
    {
        return $this->modifiedAt;
    }

    public function setModifiedAt(\DateTimeImmutable $modifiedAt): self
    {
        $this->modifiedAt = $modifiedAt;

        return $this;
    }

    /**
     * @return Collection<int, Slot>
     */
    public function getCartSlotId(): ?int
    {
        return $this->cartSlotId;
    }

    public function setCartSlotId(int $cartSlotId): self
    {
        $this->cartSlotId = $cartSlotId;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getClosedAt(): ?\DateTimeImmutable
    {
        return $this->closedAt;
    }

    public function setClosedAt(?\DateTimeImmutable $closedAt): self
    {
        $this->closedAt = $closedAt;

        return $this;
    }

    public function getNotes(): ?string
    {
        return $this->notes;
    }

    public function setNotes(?string $notes): self
    {
        $this->notes = $notes;

        return $this;
    }

    public function getItems(): ?array
    {
        return $this->items;
    }

    public function setItems(?array $items): self
    {
        $this->items = $items;

        return $this;
    }
}

src/Controller/RepairController.php
<?php

namespace App\Controller;

use App\Entity\User;
use Doctrine\ORM\EntityRepository;
use App\Repository\RepairRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class RepairController extends AbstractController
{
    #[Route('/repair', name: 'app_repair')]
    public function index(Request $request, RepairRepository $repairRepository, ManagerRegistry $doctrine): Response
    {
        $repairList = $repairRepository->getActiveRepairs();

        return $this->render('repair/index.html.twig', [
            'repairList' => $repairList,
        ]);
    } 

    #[Route('/repair/add', name: 'app_repair_add')]
    public function add(Request $request, ManagerRegistry $doctrine, Security $security): Response {
        $form = $this->createFormBuilder()
            ->add('technicianId', EntityType::class, [
                // @todo idk, wtf. not setting class gives error. class is needed. anything I put into class throws error that it's not mapped
                'class' => User::class,
                'query_builder' => function (EntityRepository $repository) {
                    $qb = $repository->createQueryBuilder('u')
                        ->select('u.id', 'u.email')
                        ->where('u.Enabled = 1')
                        ->getQuery()
                        ->getResult();

                    dump($qb);
                }
            ])
            ->getForm();

        return $this->render('repair/add.html.twig', [
            'form' => $form->createView()
        ]);
    }
}

templates/repair/add.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {{ form(form) }}
{% endblock %}

templates/repair/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello RepairController!{% endblock %}

{% block child_javascripts %}
    <script src="/js/people.js" type="text/javascript"></script>
{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="data-table">
            {% if repairList is empty %}
                <table class="table table-sm table-hover table-striped">
                    <thead>
                        <tr>
                            <th scope="col">#</td>
                            <th scope="col">Asset Tag</td>
                            <th scope="col">Assigned Slot</td>
                            <th scope="col">Assigned Person</td>
                            <th scope="col">Created At</td>
                            <th scope="col">Modified At</td>
                            <th scope="col">Modified By</td>
                            <th scope="col">Parts Needed</td>
                            <th scope="col">Actions</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td colspan="9">
                                No Data found.
                            </td>
                        </tr>
                    </tbody>
                </table>
            {% endif %}
            <div class="mb-2">
                <input class="form-control" id="filterTableInput" type="text" placeholder="Filter..." />
            </div>
            <table class="table table-sm table-hover table-striped">
                <thead>
                    <tr>
                        <th scope="col">#</td>
                        <th scope="col">Asset Tag</td>
                        <th scope="col">Assigned Slot</td>
                        <th scope="col">Assigned Person</td>
                        <th scope="col">Created At</td>
                        <th scope="col">Modified At</td>
                        <th scope="col">Modified By</td>
                        <th scope="col">Parts Needed</td>
                        <th scope="col">Actions</td>
                    </tr>
                </thead>
                <tbody id="filterableTable">
                    {% for key, repair in repairList %}
                        <tr>
                            <th scope="row">{{ loop.index0 }}</th>
                            <td>{{ repair.assetTag }}</td>
                            <td>{{ repair.slot }}</td>
                            <td>{{ repair.assignedPerson }}</td>
                            <td>{{ repair.createdAt|date('Y-m-d h:i') }}</td>
                            <td>{{ repair.modifiedAt|date('Y-m-d h:i') }}</td>
                            <td>{{ repair.technician }}</td>
                            <td>{{ repair.items|join(', ') }}</td>
                            <td>Edit | Delete</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}